// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
// RUN: %clang_cc1                                                                    -emit-llvm %s -o - -triple x86_64-linux-gnu              -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-NO-EXCEPTIONS
// RUN: %clang_cc1                                                                    -emit-llvm %s -o - -triple x86_64-linux-gnu -fexceptions -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-NOSANITIZE
// RUN: %clang_cc1 -fsanitize=exception-escape                                        -emit-llvm %s -o - -triple x86_64-linux-gnu -fexceptions -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-SANITIZE-NORECOVER
// RUN: %clang_cc1 -fsanitize=exception-escape -fno-sanitize-recover=exception-escape -emit-llvm %s -o - -triple x86_64-linux-gnu -fexceptions -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-SANITIZE-NORECOVER
// RUN: %clang_cc1 -fsanitize=exception-escape -fsanitize-trap=exception-escape       -emit-llvm %s -o - -triple x86_64-linux-gnu -fexceptions -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-SANITIZE-TRAP

void will_throw(int line = __builtin_LINE());
void might_throw(int line = __builtin_LINE());
void will_not_throw(int line = __builtin_LINE()) noexcept;

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 100) #[[ATTR4:[0-9]+]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END]]
// CHECK-NO-EXCEPTIONS:       if.end:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then2:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 300) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END3]]
// CHECK-NO-EXCEPTIONS:       if.end3:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END6:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then5:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 500)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END6]]
// CHECK-NO-EXCEPTIONS:       if.end6:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP7:%.*]] = icmp eq i32 [[TMP3]], 5
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP7]], label [[IF_THEN8:%.*]], label [[IF_END9:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then8:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 900)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END9]]
// CHECK-NO-EXCEPTIONS:       if.end9:
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NOSANITIZE: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-NOSANITIZE-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-NOSANITIZE-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NOSANITIZE-NEXT:  entry:
// CHECK-NOSANITIZE-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NOSANITIZE-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[X12:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NOSANITIZE:       if.then:
// CHECK-NOSANITIZE-NEXT:    call void @_Z10will_throwi(i32 noundef 100) #[[ATTR7:[0-9]+]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END]]
// CHECK-NOSANITIZE:       if.end:
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-NOSANITIZE:       if.then2:
// CHECK-NOSANITIZE-NEXT:    call void @_Z10will_throwi(i32 noundef 300) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END3]]
// CHECK-NOSANITIZE:       if.end3:
// CHECK-NOSANITIZE-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END6:%.*]]
// CHECK-NOSANITIZE:       if.then5:
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-NOSANITIZE:       lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH:%.*]]
// CHECK-NOSANITIZE:       catch:
// CHECK-NOSANITIZE-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    call void @_Z11might_throwi(i32 noundef 700) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    call void @__cxa_rethrow() #[[ATTR8:[0-9]+]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       try.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END6]]
// CHECK-NOSANITIZE:       if.end6:
// CHECK-NOSANITIZE-NEXT:    [[TMP7:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP7:%.*]] = icmp eq i32 [[TMP7]], 5
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP7]], label [[IF_THEN8:%.*]], label [[IF_END15:%.*]]
// CHECK-NOSANITIZE:       if.then8:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT10:%.*]] unwind label [[LPAD9:%.*]]
// CHECK-NOSANITIZE:       invoke.cont10:
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT14:%.*]]
// CHECK-NOSANITIZE:       lpad9:
// CHECK-NOSANITIZE-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr @_ZTIi
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-NOSANITIZE:       catch.dispatch:
// CHECK-NOSANITIZE-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP11:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP11]]
// CHECK-NOSANITIZE-NEXT:    br i1 [[MATCHES]], label [[CATCH11:%.*]], label [[UNREACHABLE:%.*]]
// CHECK-NOSANITIZE:       catch11:
// CHECK-NOSANITIZE-NEXT:    [[EXN13:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP12:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN13]]) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP13]], ptr [[X12]], align 4
// CHECK-NOSANITIZE-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP14:%.*]] = load i32, ptr [[X12]], align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP14]], ptr [[EXCEPTION]], align 16
// CHECK-NOSANITIZE-NEXT:    call void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR8]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       try.cont14:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END15]]
// CHECK-NOSANITIZE:       if.end15:
// CHECK-NOSANITIZE-NEXT:    ret void
// CHECK-NOSANITIZE:       unreachable:
// CHECK-NOSANITIZE-NEXT:    unreachable
//
// CHECK-SANITIZE-NORECOVER: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-SANITIZE-NORECOVER-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-SANITIZE-NORECOVER-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-NORECOVER-NEXT:  entry:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[INVOKE_SRCLOC:%.*]] = alloca { ptr, i32, i32 }, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP:%.*]] = alloca { ptr, i32, i32 }, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 100, i32 5 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 100)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-NORECOVER:       handler.exception_escape:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } [[CURR_INVOKE_SRCLOC:%.*]], ptr [[TMP]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP]] to i64, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[EXN19:%.*]] to i64, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__ubsan_handle_exception_escape(i64 [[TMP1]], i64 [[TMP2]]) #[[ATTR8:[0-9]+]], !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable, !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable, !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       if.end:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR9:[0-9]+]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP3]], 3
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then2:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 300, i32 5 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 300)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT3:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont3:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END4]]
// CHECK-SANITIZE-NORECOVER:       if.end4:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP4:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP4]], 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END9:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then6:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 500, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont7:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP6]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP7]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP8:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 700, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont8:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 800, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_rethrow() #[[ATTR10:[0-9]+]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       try.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END9]]
// CHECK-SANITIZE-NORECOVER:       if.end9:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP9:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP9]], 5
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END18:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then11:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 900, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont13:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT17:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad12:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP10:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr @_ZTIi
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i32 } [[TMP10]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP11]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i32 } [[TMP10]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP12]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch.dispatch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP13:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP13]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[EXCEPTION_ESCAPE_HANDLER:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch14:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP14:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP14]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP15]], ptr [[X15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 1000, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP16:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP16]], ptr [[EXCEPTION]], align 16
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR10]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       try.cont17:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END18]]
// CHECK-SANITIZE-NORECOVER:       if.end18:
// CHECK-SANITIZE-NORECOVER-NEXT:    ret void
// CHECK-SANITIZE-NORECOVER:       unreachable:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       exception-escape.sanitization:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN19]] = load ptr, ptr [[EXN_SLOT]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CURR_INVOKE_SRCLOC]] = load { ptr, i32, i32 }, ptr [[INVOKE_SRCLOC]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 false, label [[CONT:%.*]], label [[HANDLER_EXCEPTION_ESCAPE:%.*]], !prof [[PROF3:![0-9]+]], !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       exception-escape.lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP17:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, i32 } [[TMP17]], 0, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP18]], ptr [[EXN_SLOT]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EXCEPTION_ESCAPE_SANITIZATION:%.*]], !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       exception-escape.handler:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EXCEPTION_ESCAPE_SANITIZATION]]
//
// CHECK-SANITIZE-TRAP: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-SANITIZE-TRAP-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-SANITIZE-TRAP-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-TRAP-NEXT:  entry:
// CHECK-SANITIZE-TRAP-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[INVOKE_SRCLOC:%.*]] = alloca { ptr, i32, i32 }, align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-TRAP:       if.then:
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 100, i32 5 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 100)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-TRAP:       trap:
// CHECK-SANITIZE-TRAP-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR8:[0-9]+]], !nosanitize !2
// CHECK-SANITIZE-TRAP-NEXT:    unreachable, !nosanitize !2
// CHECK-SANITIZE-TRAP:       cont:
// CHECK-SANITIZE-TRAP-NEXT:    unreachable, !nosanitize !2
// CHECK-SANITIZE-TRAP:       if.end:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR9:[0-9]+]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-SANITIZE-TRAP:       if.then2:
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 300, i32 5 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 300)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT3:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-TRAP:       invoke.cont3:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END4]]
// CHECK-SANITIZE-TRAP:       if.end4:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END9:%.*]]
// CHECK-SANITIZE-TRAP:       if.then6:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 500, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont7:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-TRAP:       lpad:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-TRAP:       catch:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 700, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-TRAP:       invoke.cont8:
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 800, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_rethrow() #[[ATTR10:[0-9]+]]
// CHECK-SANITIZE-TRAP-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-TRAP:       try.cont:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END9]]
// CHECK-SANITIZE-TRAP:       if.end9:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP7:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP7]], 5
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END18:%.*]]
// CHECK-SANITIZE-TRAP:       if.then11:
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 900, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont13:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[TRY_CONT17:%.*]]
// CHECK-SANITIZE-TRAP:       lpad12:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr @_ZTIi
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-SANITIZE-TRAP:       catch.dispatch:
// CHECK-SANITIZE-TRAP-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP11:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP11]]
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[EXCEPTION_ESCAPE_HANDLER:%.*]]
// CHECK-SANITIZE-TRAP:       catch14:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP12:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP13]], ptr [[X15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 1000, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP14:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP14]], ptr [[EXCEPTION]], align 16
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR10]]
// CHECK-SANITIZE-TRAP-NEXT:    to label [[UNREACHABLE]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-TRAP:       try.cont17:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END18]]
// CHECK-SANITIZE-TRAP:       if.end18:
// CHECK-SANITIZE-TRAP-NEXT:    ret void
// CHECK-SANITIZE-TRAP:       unreachable:
// CHECK-SANITIZE-TRAP-NEXT:    unreachable
// CHECK-SANITIZE-TRAP:       exception-escape.sanitization:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN19:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8, !nosanitize !2
// CHECK-SANITIZE-TRAP-NEXT:    [[CURR_INVOKE_SRCLOC:%.*]] = load { ptr, i32, i32 }, ptr [[INVOKE_SRCLOC]], align 8, !nosanitize !2
// CHECK-SANITIZE-TRAP-NEXT:    br i1 false, label [[CONT:%.*]], label [[TRAP:%.*]], !nosanitize !2
// CHECK-SANITIZE-TRAP:       exception-escape.lpad:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP15:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null, !nosanitize !2
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, i32 } [[TMP15]], 0, !nosanitize !2
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP16]], ptr [[EXN_SLOT]], align 8, !nosanitize !2
// CHECK-SANITIZE-TRAP-NEXT:    br label [[EXCEPTION_ESCAPE_SANITIZATION:%.*]], !nosanitize !2
// CHECK-SANITIZE-TRAP:       exception-escape.handler:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[EXCEPTION_ESCAPE_SANITIZATION]]
//
void __attribute__((pure)) footgun_exception_escape_is_ub(int x) {
  if (x == 2) {
#line 100
    will_throw();
  }
#line 200
  will_not_throw();
  if (x == 3) {
#line 300
    will_throw();
  }
  if (x == 4) {
    try {
#line 400
      will_not_throw();
#line 500
      will_throw();
    } catch (...) {
#line 600
      will_not_throw();
#line 700
      might_throw();
#line 800
      throw;
    }
  }
  if (x == 5) {
    try {
#line 900
      will_throw();
    } catch (int x) {
#line 1000
      throw x;
    }
  }
}

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR3:[0-9]+]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 100)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END]]
// CHECK-NO-EXCEPTIONS:       if.end:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then2:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 300)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END3]]
// CHECK-NO-EXCEPTIONS:       if.end3:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END6:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then5:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 500)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END6]]
// CHECK-NO-EXCEPTIONS:       if.end6:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP7:%.*]] = icmp eq i32 [[TMP3]], 5
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP7]], label [[IF_THEN8:%.*]], label [[IF_END9:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then8:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 900)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END9]]
// CHECK-NO-EXCEPTIONS:       if.end9:
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NOSANITIZE: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NOSANITIZE-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-NOSANITIZE-SAME: (i32 noundef [[X:%.*]]) #[[ATTR4:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NOSANITIZE-NEXT:  entry:
// CHECK-NOSANITIZE-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NOSANITIZE-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NOSANITIZE:       if.then:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 100)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END]]
// CHECK-NOSANITIZE:       if.end:
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-NOSANITIZE:       if.then2:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 300)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT3:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       invoke.cont3:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END4]]
// CHECK-NOSANITIZE:       if.end4:
// CHECK-NOSANITIZE-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END9:%.*]]
// CHECK-NOSANITIZE:       if.then6:
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont7:
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-NOSANITIZE:       lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH:%.*]]
// CHECK-NOSANITIZE:       catch:
// CHECK-NOSANITIZE-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       invoke.cont8:
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_rethrow() #[[ATTR8]]
// CHECK-NOSANITIZE-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       try.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END9]]
// CHECK-NOSANITIZE:       if.end9:
// CHECK-NOSANITIZE-NEXT:    [[TMP7:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP7]], 5
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END18:%.*]]
// CHECK-NOSANITIZE:       if.then11:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-NOSANITIZE:       invoke.cont13:
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT17:%.*]]
// CHECK-NOSANITIZE:       lpad12:
// CHECK-NOSANITIZE-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr @_ZTIi
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-NOSANITIZE:       catch.dispatch:
// CHECK-NOSANITIZE-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP11:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP11]]
// CHECK-NOSANITIZE-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[TERMINATE_HANDLER:%.*]]
// CHECK-NOSANITIZE:       catch14:
// CHECK-NOSANITIZE-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP12:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP13]], ptr [[X15]], align 4
// CHECK-NOSANITIZE-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP14:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP14]], ptr [[EXCEPTION]], align 16
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR8]]
// CHECK-NOSANITIZE-NEXT:    to label [[UNREACHABLE]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       try.cont17:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END18]]
// CHECK-NOSANITIZE:       if.end18:
// CHECK-NOSANITIZE-NEXT:    ret void
// CHECK-NOSANITIZE:       terminate.lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP15:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, i32 } [[TMP15]], 0
// CHECK-NOSANITIZE-NEXT:    call void @__clang_call_terminate(ptr [[TMP16]]) #[[ATTR9:[0-9]+]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       terminate.handler:
// CHECK-NOSANITIZE-NEXT:    [[EXN19:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    call void @__clang_call_terminate(ptr [[EXN19]]) #[[ATTR9]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       unreachable:
// CHECK-NOSANITIZE-NEXT:    unreachable
//
// CHECK-SANITIZE-NORECOVER: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-SANITIZE-NORECOVER-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-SANITIZE-NORECOVER-SAME: (i32 noundef [[X:%.*]]) #[[ATTR5:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-NORECOVER-NEXT:  entry:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 100)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-NORECOVER:       if.end:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then2:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 300)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT3:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont3:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END4]]
// CHECK-SANITIZE-NORECOVER:       if.end4:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END9:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then6:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont7:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont8:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_rethrow() #[[ATTR10]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       try.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END9]]
// CHECK-SANITIZE-NORECOVER:       if.end9:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP7:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP7]], 5
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END18:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then11:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont13:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT17:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad12:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr @_ZTIi
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch.dispatch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP11:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP11]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[TERMINATE_HANDLER:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch14:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP12:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP13]], ptr [[X15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP14:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP14]], ptr [[EXCEPTION]], align 16
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR10]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       try.cont17:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END18]]
// CHECK-SANITIZE-NORECOVER:       if.end18:
// CHECK-SANITIZE-NORECOVER-NEXT:    ret void
// CHECK-SANITIZE-NORECOVER:       terminate.lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP15:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, i32 } [[TMP15]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__clang_call_terminate(ptr [[TMP16]]) #[[ATTR8]]
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       terminate.handler:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN19:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__clang_call_terminate(ptr [[EXN19]]) #[[ATTR8]]
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       unreachable:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
//
// CHECK-SANITIZE-TRAP: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-SANITIZE-TRAP-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-SANITIZE-TRAP-SAME: (i32 noundef [[X:%.*]]) #[[ATTR5:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-TRAP-NEXT:  entry:
// CHECK-SANITIZE-TRAP-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-TRAP:       if.then:
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 100)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-TRAP:       if.end:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-SANITIZE-TRAP:       if.then2:
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 300)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT3:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-TRAP:       invoke.cont3:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END4]]
// CHECK-SANITIZE-TRAP:       if.end4:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END9:%.*]]
// CHECK-SANITIZE-TRAP:       if.then6:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont7:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-TRAP:       lpad:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-TRAP:       catch:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-TRAP:       invoke.cont8:
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_rethrow() #[[ATTR10]]
// CHECK-SANITIZE-TRAP-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-TRAP:       try.cont:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END9]]
// CHECK-SANITIZE-TRAP:       if.end9:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP7:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP7]], 5
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END18:%.*]]
// CHECK-SANITIZE-TRAP:       if.then11:
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont13:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[TRY_CONT17:%.*]]
// CHECK-SANITIZE-TRAP:       lpad12:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr @_ZTIi
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-SANITIZE-TRAP:       catch.dispatch:
// CHECK-SANITIZE-TRAP-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP11:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP11]]
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[TERMINATE_HANDLER:%.*]]
// CHECK-SANITIZE-TRAP:       catch14:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP12:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP13]], ptr [[X15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP14:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP14]], ptr [[EXCEPTION]], align 16
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR10]]
// CHECK-SANITIZE-TRAP-NEXT:    to label [[UNREACHABLE]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-TRAP:       try.cont17:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END18]]
// CHECK-SANITIZE-TRAP:       if.end18:
// CHECK-SANITIZE-TRAP-NEXT:    ret void
// CHECK-SANITIZE-TRAP:       terminate.lpad:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP15:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP16:%.*]] = extractvalue { ptr, i32 } [[TMP15]], 0
// CHECK-SANITIZE-TRAP-NEXT:    call void @__clang_call_terminate(ptr [[TMP16]]) #[[ATTR8]]
// CHECK-SANITIZE-TRAP-NEXT:    unreachable
// CHECK-SANITIZE-TRAP:       terminate.handler:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN19:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    call void @__clang_call_terminate(ptr [[EXN19]]) #[[ATTR8]]
// CHECK-SANITIZE-TRAP-NEXT:    unreachable
// CHECK-SANITIZE-TRAP:       unreachable:
// CHECK-SANITIZE-TRAP-NEXT:    unreachable
//
void exception_escape_is_program_termination(int x) noexcept {
  if (x == 2) {
#line 100
    will_throw();
  }
#line 200
  will_not_throw();
  if (x == 3) {
#line 300
    will_throw();
  }
  if (x == 4) {
    try {
#line 400
      will_not_throw();
#line 500
      will_throw();
    } catch (...) {
#line 600
      will_not_throw();
#line 700
      might_throw();
#line 800
      throw;
    }
  }
  if (x == 5) {
    try {
#line 900
      will_throw();
    } catch (int x) {
#line 1000
      throw x;
    }
  }
}

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR3]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 100)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END]]
// CHECK-NO-EXCEPTIONS:       if.end:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then2:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 300)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END3]]
// CHECK-NO-EXCEPTIONS:       if.end3:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END6:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then5:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 500)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END6]]
// CHECK-NO-EXCEPTIONS:       if.end6:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP7:%.*]] = icmp eq i32 [[TMP3]], 5
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP7]], label [[IF_THEN8:%.*]], label [[IF_END9:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then8:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 900)
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END9]]
// CHECK-NO-EXCEPTIONS:       if.end9:
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NOSANITIZE: Function Attrs: mustprogress noinline optnone
// CHECK-NOSANITIZE-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-NOSANITIZE-SAME: (i32 noundef [[X:%.*]]) #[[ATTR6:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NOSANITIZE-NEXT:  entry:
// CHECK-NOSANITIZE-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NOSANITIZE-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NOSANITIZE:       if.then:
// CHECK-NOSANITIZE-NEXT:    call void @_Z10will_throwi(i32 noundef 100)
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END]]
// CHECK-NOSANITIZE:       if.end:
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-NOSANITIZE:       if.then2:
// CHECK-NOSANITIZE-NEXT:    call void @_Z10will_throwi(i32 noundef 300)
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END3]]
// CHECK-NOSANITIZE:       if.end3:
// CHECK-NOSANITIZE-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END9:%.*]]
// CHECK-NOSANITIZE:       if.then5:
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-NOSANITIZE:       lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH:%.*]]
// CHECK-NOSANITIZE:       catch:
// CHECK-NOSANITIZE-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-NOSANITIZE:       invoke.cont7:
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_rethrow() #[[ATTR8]]
// CHECK-NOSANITIZE-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[LPAD6]]
// CHECK-NOSANITIZE:       lpad6:
// CHECK-NOSANITIZE-NEXT:    [[TMP7:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    cleanup
// CHECK-NOSANITIZE-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP8]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP9]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_end_catch()
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont8:
// CHECK-NOSANITIZE-NEXT:    br label [[EH_RESUME:%.*]]
// CHECK-NOSANITIZE:       try.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END9]]
// CHECK-NOSANITIZE:       if.end9:
// CHECK-NOSANITIZE-NEXT:    [[TMP10:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP10]], 5
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END19:%.*]]
// CHECK-NOSANITIZE:       if.then11:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-NOSANITIZE:       invoke.cont13:
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT18:%.*]]
// CHECK-NOSANITIZE:       lpad12:
// CHECK-NOSANITIZE-NEXT:    [[TMP11:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr @_ZTIi
// CHECK-NOSANITIZE-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i32 } [[TMP11]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP12]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i32 } [[TMP11]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP13]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-NOSANITIZE:       catch.dispatch:
// CHECK-NOSANITIZE-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP14:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP14]]
// CHECK-NOSANITIZE-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[EH_RESUME]]
// CHECK-NOSANITIZE:       catch14:
// CHECK-NOSANITIZE-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP15:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP16:%.*]] = load i32, ptr [[TMP15]], align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP16]], ptr [[X15]], align 4
// CHECK-NOSANITIZE-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    [[TMP17:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP17]], ptr [[EXCEPTION]], align 16
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR8]]
// CHECK-NOSANITIZE-NEXT:    to label [[UNREACHABLE]] unwind label [[LPAD17:%.*]]
// CHECK-NOSANITIZE:       lpad17:
// CHECK-NOSANITIZE-NEXT:    [[TMP18:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    cleanup
// CHECK-NOSANITIZE-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i32 } [[TMP18]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP19]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, i32 } [[TMP18]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP20]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    call void @__cxa_end_catch() #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    br label [[EH_RESUME]]
// CHECK-NOSANITIZE:       try.cont18:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END19]]
// CHECK-NOSANITIZE:       if.end19:
// CHECK-NOSANITIZE-NEXT:    ret void
// CHECK-NOSANITIZE:       eh.resume:
// CHECK-NOSANITIZE-NEXT:    [[EXN20:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[SEL21:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } undef, ptr [[EXN20]], 0
// CHECK-NOSANITIZE-NEXT:    [[LPAD_VAL22:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL21]], 1
// CHECK-NOSANITIZE-NEXT:    resume { ptr, i32 } [[LPAD_VAL22]]
// CHECK-NOSANITIZE:       terminate.lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP21:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, i32 } [[TMP21]], 0
// CHECK-NOSANITIZE-NEXT:    call void @__clang_call_terminate(ptr [[TMP22]]) #[[ATTR9]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       unreachable:
// CHECK-NOSANITIZE-NEXT:    unreachable
//
// CHECK-SANITIZE-NORECOVER: Function Attrs: mustprogress noinline optnone
// CHECK-SANITIZE-NORECOVER-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-SANITIZE-NORECOVER-SAME: (i32 noundef [[X:%.*]]) #[[ATTR7:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-NORECOVER-NEXT:  entry:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z10will_throwi(i32 noundef 100)
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-NORECOVER:       if.end:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then2:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z10will_throwi(i32 noundef 300)
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END3]]
// CHECK-SANITIZE-NORECOVER:       if.end3:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END9:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then5:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont7:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_rethrow() #[[ATTR10]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[LPAD6]]
// CHECK-SANITIZE-NORECOVER:       lpad6:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP7:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    cleanup
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP8]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP9]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_end_catch()
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont8:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EH_RESUME:%.*]]
// CHECK-SANITIZE-NORECOVER:       try.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END9]]
// CHECK-SANITIZE-NORECOVER:       if.end9:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP10:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP10]], 5
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END19:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then11:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont13:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT18:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad12:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP11:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr @_ZTIi
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i32 } [[TMP11]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP12]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i32 } [[TMP11]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP13]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       catch.dispatch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP14:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP14]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[EH_RESUME]]
// CHECK-SANITIZE-NORECOVER:       catch14:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP15:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP16:%.*]] = load i32, ptr [[TMP15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP16]], ptr [[X15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP17:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP17]], ptr [[EXCEPTION]], align 16
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR10]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE]] unwind label [[LPAD17:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad17:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP18:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    cleanup
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i32 } [[TMP18]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP19]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, i32 } [[TMP18]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP20]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__cxa_end_catch() #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EH_RESUME]]
// CHECK-SANITIZE-NORECOVER:       try.cont18:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END19]]
// CHECK-SANITIZE-NORECOVER:       if.end19:
// CHECK-SANITIZE-NORECOVER-NEXT:    ret void
// CHECK-SANITIZE-NORECOVER:       eh.resume:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN20:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[SEL21:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } undef, ptr [[EXN20]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    [[LPAD_VAL22:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL21]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    resume { ptr, i32 } [[LPAD_VAL22]]
// CHECK-SANITIZE-NORECOVER:       terminate.lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP21:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, i32 } [[TMP21]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__clang_call_terminate(ptr [[TMP22]]) #[[ATTR8]]
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       unreachable:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
//
// CHECK-SANITIZE-TRAP: Function Attrs: mustprogress noinline optnone
// CHECK-SANITIZE-TRAP-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-SANITIZE-TRAP-SAME: (i32 noundef [[X:%.*]]) #[[ATTR7:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-TRAP-NEXT:  entry:
// CHECK-SANITIZE-TRAP-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[X15:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 2
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-TRAP:       if.then:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z10will_throwi(i32 noundef 100)
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-TRAP:       if.end:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 200) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 3
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END3:%.*]]
// CHECK-SANITIZE-TRAP:       if.then2:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z10will_throwi(i32 noundef 300)
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END3]]
// CHECK-SANITIZE-TRAP:       if.end3:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP2]], 4
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP4]], label [[IF_THEN5:%.*]], label [[IF_END9:%.*]]
// CHECK-SANITIZE-TRAP:       if.then5:
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 400) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 500)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-TRAP:       lpad:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-TRAP:       catch:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP6:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    call void @_Z14will_not_throwi(i32 noundef 600) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z11might_throwi(i32 noundef 700)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont7:
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_rethrow() #[[ATTR10]]
// CHECK-SANITIZE-TRAP-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[LPAD6]]
// CHECK-SANITIZE-TRAP:       lpad6:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP7:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    cleanup
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP8]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP9]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_end_catch()
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT8:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont8:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[EH_RESUME:%.*]]
// CHECK-SANITIZE-TRAP:       try.cont:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END9]]
// CHECK-SANITIZE-TRAP:       if.end9:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP10:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP10]], 5
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[CMP10]], label [[IF_THEN11:%.*]], label [[IF_END19:%.*]]
// CHECK-SANITIZE-TRAP:       if.then11:
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @_Z10will_throwi(i32 noundef 900)
// CHECK-SANITIZE-TRAP-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[LPAD12:%.*]]
// CHECK-SANITIZE-TRAP:       invoke.cont13:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[TRY_CONT18:%.*]]
// CHECK-SANITIZE-TRAP:       lpad12:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP11:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr @_ZTIi
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP12:%.*]] = extractvalue { ptr, i32 } [[TMP11]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP12]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i32 } [[TMP11]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP13]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    br label [[CATCH_DISPATCH:%.*]]
// CHECK-SANITIZE-TRAP:       catch.dispatch:
// CHECK-SANITIZE-TRAP-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP14:%.*]] = call i32 @llvm.eh.typeid.for(ptr @_ZTIi) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[MATCHES:%.*]] = icmp eq i32 [[SEL]], [[TMP14]]
// CHECK-SANITIZE-TRAP-NEXT:    br i1 [[MATCHES]], label [[CATCH14:%.*]], label [[EH_RESUME]]
// CHECK-SANITIZE-TRAP:       catch14:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN16:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP15:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN16]]) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP16:%.*]] = load i32, ptr [[TMP15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP16]], ptr [[X15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[EXCEPTION:%.*]] = call ptr @__cxa_allocate_exception(i64 4) #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP17:%.*]] = load i32, ptr [[X15]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP17]], ptr [[EXCEPTION]], align 16
// CHECK-SANITIZE-TRAP-NEXT:    invoke void @__cxa_throw(ptr [[EXCEPTION]], ptr @_ZTIi, ptr null) #[[ATTR10]]
// CHECK-SANITIZE-TRAP-NEXT:    to label [[UNREACHABLE]] unwind label [[LPAD17:%.*]]
// CHECK-SANITIZE-TRAP:       lpad17:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP18:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    cleanup
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP19:%.*]] = extractvalue { ptr, i32 } [[TMP18]], 0
// CHECK-SANITIZE-TRAP-NEXT:    store ptr [[TMP19]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, i32 } [[TMP18]], 1
// CHECK-SANITIZE-TRAP-NEXT:    store i32 [[TMP20]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    call void @__cxa_end_catch() #[[ATTR9]]
// CHECK-SANITIZE-TRAP-NEXT:    br label [[EH_RESUME]]
// CHECK-SANITIZE-TRAP:       try.cont18:
// CHECK-SANITIZE-TRAP-NEXT:    br label [[IF_END19]]
// CHECK-SANITIZE-TRAP:       if.end19:
// CHECK-SANITIZE-TRAP-NEXT:    ret void
// CHECK-SANITIZE-TRAP:       eh.resume:
// CHECK-SANITIZE-TRAP-NEXT:    [[EXN20:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-TRAP-NEXT:    [[SEL21:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-TRAP-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } undef, ptr [[EXN20]], 0
// CHECK-SANITIZE-TRAP-NEXT:    [[LPAD_VAL22:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL21]], 1
// CHECK-SANITIZE-TRAP-NEXT:    resume { ptr, i32 } [[LPAD_VAL22]]
// CHECK-SANITIZE-TRAP:       terminate.lpad:
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP21:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-TRAP-NEXT:    catch ptr null
// CHECK-SANITIZE-TRAP-NEXT:    [[TMP22:%.*]] = extractvalue { ptr, i32 } [[TMP21]], 0
// CHECK-SANITIZE-TRAP-NEXT:    call void @__clang_call_terminate(ptr [[TMP22]]) #[[ATTR8]]
// CHECK-SANITIZE-TRAP-NEXT:    unreachable
// CHECK-SANITIZE-TRAP:       unreachable:
// CHECK-SANITIZE-TRAP-NEXT:    unreachable
//
void exception_escape_is_ok(int x) {
  if (x == 2) {
#line 100
    will_throw();
  }
#line 200
  will_not_throw();
  if (x == 3) {
#line 300
    will_throw();
  }
  if (x == 4) {
    try {
#line 400
      will_not_throw();
#line 500
      will_throw();
    } catch (...) {
#line 600
      will_not_throw();
#line 700
      might_throw();
#line 800
      throw;
    }
  }
  if (x == 5) {
    try {
#line 900
      will_throw();
    } catch (int x) {
#line 1000
      throw x;
    }
  }
}
