// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
// RUN: %clang_cc1                             -emit-llvm %s -o - -triple x86_64-linux-gnu              -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-NO-EXCEPTIONS
// RUN: %clang_cc1                             -emit-llvm %s -o - -triple x86_64-linux-gnu -fexceptions -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-NOSANITIZE
// RUN: %clang_cc1 -fsanitize=exception-escape -emit-llvm %s -o - -triple x86_64-linux-gnu -fexceptions -fcxx-exceptions | FileCheck %s --check-prefixes=CHECK-SANITIZE-NORECOVER

void will_throw(int line = __builtin_LINE());
void might_throw(int line = __builtin_LINE());
void will_not_throw(int line = __builtin_LINE()) noexcept;

struct S {
  S(int line = __builtin_LINE());
  ~S();
};

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE3:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE7:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100) #[[ATTR4:[0-9]+]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z11might_throwi(i32 noundef 200) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END]]
// CHECK-NO-EXCEPTIONS:       if.end:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 1
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then2:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]], i32 noundef 300)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z11might_throwi(i32 noundef 400)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END4]]
// CHECK-NO-EXCEPTIONS:       if.end4:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 2
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END8:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then6:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE7]], i32 noundef 600) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 700) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE7]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END8]]
// CHECK-NO-EXCEPTIONS:       if.end8:
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NOSANITIZE: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-NOSANITIZE-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-NOSANITIZE-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NOSANITIZE-NEXT:  entry:
// CHECK-NOSANITIZE-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NOSANITIZE-NEXT:    [[STATE3:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NOSANITIZE-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NOSANITIZE-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[STATE9:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NOSANITIZE:       if.then:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100) #[[ATTR6:[0-9]+]]
// CHECK-NOSANITIZE-NEXT:    call void @_Z11might_throwi(i32 noundef 200) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END]]
// CHECK-NOSANITIZE:       if.end:
// CHECK-NOSANITIZE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 1
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END6:%.*]]
// CHECK-NOSANITIZE:       if.then2:
// CHECK-NOSANITIZE-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]], i32 noundef 300)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 400)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT5:%.*]] unwind label [[LPAD4:%.*]]
// CHECK-NOSANITIZE:       invoke.cont5:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-NOSANITIZE:       lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP2:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, i32 } [[TMP2]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP3]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP2]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP4]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH:%.*]]
// CHECK-NOSANITIZE:       lpad4:
// CHECK-NOSANITIZE-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP6]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP7]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH]]
// CHECK-NOSANITIZE:       catch:
// CHECK-NOSANITIZE-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP8:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    call void @__cxa_rethrow() #[[ATTR7:[0-9]+]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       try.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END6]]
// CHECK-NOSANITIZE:       if.end6:
// CHECK-NOSANITIZE-NEXT:    [[TMP9:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP7:%.*]] = icmp eq i32 [[TMP9]], 2
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP7]], label [[IF_THEN8:%.*]], label [[IF_END10:%.*]]
// CHECK-NOSANITIZE:       if.then8:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE9]], i32 noundef 600) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    call void @_Z10will_throwi(i32 noundef 700) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE9]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END10]]
// CHECK-NOSANITIZE:       if.end10:
// CHECK-NOSANITIZE-NEXT:    ret void
//
// CHECK-SANITIZE-NORECOVER: Function Attrs: mustprogress noinline nounwind optnone willreturn memory(read)
// CHECK-SANITIZE-NORECOVER-LABEL: define {{[^@]+}}@_Z30footgun_exception_escape_is_ubi
// CHECK-SANITIZE-NORECOVER-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-NORECOVER-NEXT:  entry:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[INVOKE_SRCLOC:%.*]] = alloca { ptr, i32, i32 }, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP:%.*]] = alloca { ptr, i32, i32 }, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE4:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE11:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 100, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 200, i32 5 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 200)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT1:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont1:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR7:[0-9]+]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-NORECOVER:       handler.exception_escape:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } [[CURR_INVOKE_SRCLOC:%.*]], ptr [[TMP]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP]] to i64, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[EXN15:%.*]] to i64, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__ubsan_handle_exception_escape(i64 [[TMP1]], i64 [[TMP2]]) #[[ATTR8:[0-9]+]], !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable, !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable, !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       if.end:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TMP3]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP2]], label [[IF_THEN3:%.*]], label [[IF_END8:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then3:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 300, i32 9 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]], i32 noundef 300)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT5:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont5:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 400, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 400)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont7:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP4:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP4]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP5]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP4]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP6]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad6:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP7:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP8]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP7]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP9]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH]]
// CHECK-SANITIZE-NORECOVER:       catch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP10:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 500, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_rethrow() #[[ATTR9:[0-9]+]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       try.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END8]]
// CHECK-SANITIZE-NORECOVER:       if.end8:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP11:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP9:%.*]] = icmp eq i32 [[TMP11]], 2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP9]], label [[IF_THEN10:%.*]], label [[IF_END14:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then10:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 600, i32 7 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE11]], i32 noundef 600)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT12:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont12:
// CHECK-SANITIZE-NORECOVER-NEXT:    store { ptr, i32, i32 } { ptr @.src, i32 700, i32 5 }, ptr [[INVOKE_SRCLOC]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 700)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[EXCEPTION_ESCAPE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont13:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE11]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END14]]
// CHECK-SANITIZE-NORECOVER:       if.end14:
// CHECK-SANITIZE-NORECOVER-NEXT:    ret void
// CHECK-SANITIZE-NORECOVER:       unreachable:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       exception-escape.sanitization:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN15]] = load ptr, ptr [[EXN_SLOT]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CURR_INVOKE_SRCLOC]] = load { ptr, i32, i32 }, ptr [[INVOKE_SRCLOC]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 false, label [[CONT:%.*]], label [[HANDLER_EXCEPTION_ESCAPE:%.*]], !prof [[PROF3:![0-9]+]], !nosanitize !2
// CHECK-SANITIZE-NORECOVER:       exception-escape.lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP12:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i32 } [[TMP12]], 0, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP13]], ptr [[EXN_SLOT]], align 8, !nosanitize !2
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EXCEPTION_ESCAPE_SANITIZATION:%.*]], !nosanitize !2
//
void __attribute__((pure)) footgun_exception_escape_is_ub(int x) {
  if(x == 0) {
#line 100
    S state;
#line 200
    might_throw();
  }
  if(x == 1) {
    try {
#line 300
      S state;
#line 400
      might_throw();
    } catch (...) {
#line 500
      throw;
    }
  }
  if(x == 2) {
#line 600
    S state;
#line 700
    will_throw();
  }
}

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR3:[0-9]+]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE3:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE7:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z11might_throwi(i32 noundef 200)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END]]
// CHECK-NO-EXCEPTIONS:       if.end:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 1
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then2:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]], i32 noundef 300)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z11might_throwi(i32 noundef 400)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END4]]
// CHECK-NO-EXCEPTIONS:       if.end4:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 2
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END8:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then6:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE7]], i32 noundef 600)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 700)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE7]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END8]]
// CHECK-NO-EXCEPTIONS:       if.end8:
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NOSANITIZE: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NOSANITIZE-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-NOSANITIZE-SAME: (i32 noundef [[X:%.*]]) #[[ATTR3:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NOSANITIZE-NEXT:  entry:
// CHECK-NOSANITIZE-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NOSANITIZE-NEXT:    [[STATE4:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NOSANITIZE-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NOSANITIZE-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[STATE11:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NOSANITIZE:       if.then:
// CHECK-NOSANITIZE-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 200)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT1:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       invoke.cont1:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END]]
// CHECK-NOSANITIZE:       if.end:
// CHECK-NOSANITIZE-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TMP1]], 1
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP2]], label [[IF_THEN3:%.*]], label [[IF_END8:%.*]]
// CHECK-NOSANITIZE:       if.then3:
// CHECK-NOSANITIZE-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]], i32 noundef 300)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT5:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont5:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 400)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-NOSANITIZE:       invoke.cont7:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-NOSANITIZE:       lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP2:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, i32 } [[TMP2]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP3]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP2]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP4]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH:%.*]]
// CHECK-NOSANITIZE:       lpad6:
// CHECK-NOSANITIZE-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP6]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP7]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH]]
// CHECK-NOSANITIZE:       catch:
// CHECK-NOSANITIZE-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP8:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_rethrow() #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       try.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END8]]
// CHECK-NOSANITIZE:       if.end8:
// CHECK-NOSANITIZE-NEXT:    [[TMP9:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP9:%.*]] = icmp eq i32 [[TMP9]], 2
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP9]], label [[IF_THEN10:%.*]], label [[IF_END14:%.*]]
// CHECK-NOSANITIZE:       if.then10:
// CHECK-NOSANITIZE-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE11]], i32 noundef 600)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT12:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       invoke.cont12:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 700)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-NOSANITIZE:       invoke.cont13:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE11]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END14]]
// CHECK-NOSANITIZE:       if.end14:
// CHECK-NOSANITIZE-NEXT:    ret void
// CHECK-NOSANITIZE:       terminate.lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP10:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i32 } [[TMP10]], 0
// CHECK-NOSANITIZE-NEXT:    call void @__clang_call_terminate(ptr [[TMP11]]) #[[ATTR8:[0-9]+]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       unreachable:
// CHECK-NOSANITIZE-NEXT:    unreachable
//
// CHECK-SANITIZE-NORECOVER: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-SANITIZE-NORECOVER-LABEL: define {{[^@]+}}@_Z39exception_escape_is_program_terminationi
// CHECK-SANITIZE-NORECOVER-SAME: (i32 noundef [[X:%.*]]) #[[ATTR4:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-NORECOVER-NEXT:  entry:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE4:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE11:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 200)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT1:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont1:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-NORECOVER:       if.end:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TMP1]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP2]], label [[IF_THEN3:%.*]], label [[IF_END8:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then3:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]], i32 noundef 300)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT5:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont5:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 400)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont7:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP2:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, i32 } [[TMP2]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP3]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP2]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP4]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad6:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP6]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP7]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE4]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH]]
// CHECK-SANITIZE-NORECOVER:       catch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP8:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_rethrow() #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       try.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END8]]
// CHECK-SANITIZE-NORECOVER:       if.end8:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP9:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP9:%.*]] = icmp eq i32 [[TMP9]], 2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP9]], label [[IF_THEN10:%.*]], label [[IF_END14:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then10:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE11]], i32 noundef 600)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT12:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont12:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 700)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT13:%.*]] unwind label [[TERMINATE_LPAD]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont13:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE11]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END14]]
// CHECK-SANITIZE-NORECOVER:       if.end14:
// CHECK-SANITIZE-NORECOVER-NEXT:    ret void
// CHECK-SANITIZE-NORECOVER:       terminate.lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP10:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP11:%.*]] = extractvalue { ptr, i32 } [[TMP10]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__clang_call_terminate(ptr [[TMP11]]) #[[ATTR8]]
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       unreachable:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
//
void exception_escape_is_program_termination(int x) noexcept {
  if(x == 0) {
#line 100
    S state;
#line 200
    might_throw();
  }
  if(x == 1) {
    try {
#line 300
      S state;
#line 400
      might_throw();
    } catch (...) {
#line 500
      throw;
    }
  }
  if(x == 2) {
#line 600
    S state;
#line 700
    will_throw();
  }
}

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR3]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE3:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    [[STATE7:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z11might_throwi(i32 noundef 200)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END]]
// CHECK-NO-EXCEPTIONS:       if.end:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], 1
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END4:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then2:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]], i32 noundef 300)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z11might_throwi(i32 noundef 400)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END4]]
// CHECK-NO-EXCEPTIONS:       if.end4:
// CHECK-NO-EXCEPTIONS-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 2
// CHECK-NO-EXCEPTIONS-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[IF_END8:%.*]]
// CHECK-NO-EXCEPTIONS:       if.then6:
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE7]], i32 noundef 600)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z10will_throwi(i32 noundef 700)
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE7]]) #[[ATTR4]]
// CHECK-NO-EXCEPTIONS-NEXT:    br label [[IF_END8]]
// CHECK-NO-EXCEPTIONS:       if.end8:
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NOSANITIZE: Function Attrs: mustprogress noinline optnone
// CHECK-NOSANITIZE-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-NOSANITIZE-SAME: (i32 noundef [[X:%.*]]) #[[ATTR5:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NOSANITIZE-NEXT:  entry:
// CHECK-NOSANITIZE-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NOSANITIZE-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NOSANITIZE-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NOSANITIZE-NEXT:    [[STATE3:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NOSANITIZE-NEXT:    [[STATE13:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-NOSANITIZE:       if.then:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 200)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END]]
// CHECK-NOSANITIZE:       lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP1:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    cleanup
// CHECK-NOSANITIZE-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, i32 } [[TMP1]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP2]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, i32 } [[TMP1]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP3]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[EH_RESUME:%.*]]
// CHECK-NOSANITIZE:       if.end:
// CHECK-NOSANITIZE-NEXT:    [[TMP4:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP4]], 1
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END10:%.*]]
// CHECK-NOSANITIZE:       if.then2:
// CHECK-NOSANITIZE-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]], i32 noundef 300)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT5:%.*]] unwind label [[LPAD4:%.*]]
// CHECK-NOSANITIZE:       invoke.cont5:
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z11might_throwi(i32 noundef 400)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-NOSANITIZE:       invoke.cont7:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-NOSANITIZE:       lpad4:
// CHECK-NOSANITIZE-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP6]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP7]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH:%.*]]
// CHECK-NOSANITIZE:       lpad6:
// CHECK-NOSANITIZE-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[CATCH]]
// CHECK-NOSANITIZE:       catch:
// CHECK-NOSANITIZE-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP11:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_rethrow() #[[ATTR7]]
// CHECK-NOSANITIZE-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[LPAD8:%.*]]
// CHECK-NOSANITIZE:       lpad8:
// CHECK-NOSANITIZE-NEXT:    [[TMP12:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    cleanup
// CHECK-NOSANITIZE-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i32 } [[TMP12]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP13]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i32 } [[TMP12]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP14]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    invoke void @__cxa_end_catch()
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT9:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-NOSANITIZE:       invoke.cont9:
// CHECK-NOSANITIZE-NEXT:    br label [[EH_RESUME]]
// CHECK-NOSANITIZE:       try.cont:
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END10]]
// CHECK-NOSANITIZE:       if.end10:
// CHECK-NOSANITIZE-NEXT:    [[TMP15:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NOSANITIZE-NEXT:    [[CMP11:%.*]] = icmp eq i32 [[TMP15]], 2
// CHECK-NOSANITIZE-NEXT:    br i1 [[CMP11]], label [[IF_THEN12:%.*]], label [[IF_END16:%.*]]
// CHECK-NOSANITIZE:       if.then12:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE13]], i32 noundef 600)
// CHECK-NOSANITIZE-NEXT:    invoke void @_Z10will_throwi(i32 noundef 700)
// CHECK-NOSANITIZE-NEXT:    to label [[INVOKE_CONT15:%.*]] unwind label [[LPAD14:%.*]]
// CHECK-NOSANITIZE:       invoke.cont15:
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE13]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[IF_END16]]
// CHECK-NOSANITIZE:       lpad14:
// CHECK-NOSANITIZE-NEXT:    [[TMP16:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    cleanup
// CHECK-NOSANITIZE-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, i32 } [[TMP16]], 0
// CHECK-NOSANITIZE-NEXT:    store ptr [[TMP17]], ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, i32 } [[TMP16]], 1
// CHECK-NOSANITIZE-NEXT:    store i32 [[TMP18]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE13]]) #[[ATTR6]]
// CHECK-NOSANITIZE-NEXT:    br label [[EH_RESUME]]
// CHECK-NOSANITIZE:       if.end16:
// CHECK-NOSANITIZE-NEXT:    ret void
// CHECK-NOSANITIZE:       eh.resume:
// CHECK-NOSANITIZE-NEXT:    [[EXN17:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NOSANITIZE-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NOSANITIZE-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } undef, ptr [[EXN17]], 0
// CHECK-NOSANITIZE-NEXT:    [[LPAD_VAL18:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL]], 1
// CHECK-NOSANITIZE-NEXT:    resume { ptr, i32 } [[LPAD_VAL18]]
// CHECK-NOSANITIZE:       terminate.lpad:
// CHECK-NOSANITIZE-NEXT:    [[TMP19:%.*]] = landingpad { ptr, i32 }
// CHECK-NOSANITIZE-NEXT:    catch ptr null
// CHECK-NOSANITIZE-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, i32 } [[TMP19]], 0
// CHECK-NOSANITIZE-NEXT:    call void @__clang_call_terminate(ptr [[TMP20]]) #[[ATTR8]]
// CHECK-NOSANITIZE-NEXT:    unreachable
// CHECK-NOSANITIZE:       unreachable:
// CHECK-NOSANITIZE-NEXT:    unreachable
//
// CHECK-SANITIZE-NORECOVER: Function Attrs: mustprogress noinline optnone
// CHECK-SANITIZE-NORECOVER-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-SANITIZE-NORECOVER-SAME: (i32 noundef [[X:%.*]]) #[[ATTR6:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-SANITIZE-NORECOVER-NEXT:  entry:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE3:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    [[STATE13:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP0]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]], i32 noundef 100)
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 200)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END]]
// CHECK-SANITIZE-NORECOVER:       lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP1:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    cleanup
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, i32 } [[TMP1]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP2]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP3:%.*]] = extractvalue { ptr, i32 } [[TMP1]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP3]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EH_RESUME:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.end:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP4:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP4]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END10:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then2:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]], i32 noundef 300)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT5:%.*]] unwind label [[LPAD4:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont5:
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z11might_throwi(i32 noundef 400)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT7:%.*]] unwind label [[LPAD6:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont7:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[TRY_CONT:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad4:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP6:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP6]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP5]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP7]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad6:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP8:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP9:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP9]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP10:%.*]] = extractvalue { ptr, i32 } [[TMP8]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP10]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE3]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[CATCH]]
// CHECK-SANITIZE-NORECOVER:       catch:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP11:%.*]] = call ptr @__cxa_begin_catch(ptr [[EXN]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_rethrow() #[[ATTR9]]
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[UNREACHABLE:%.*]] unwind label [[LPAD8:%.*]]
// CHECK-SANITIZE-NORECOVER:       lpad8:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP12:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    cleanup
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP13:%.*]] = extractvalue { ptr, i32 } [[TMP12]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP13]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP14:%.*]] = extractvalue { ptr, i32 } [[TMP12]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP14]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @__cxa_end_catch()
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT9:%.*]] unwind label [[TERMINATE_LPAD:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont9:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EH_RESUME]]
// CHECK-SANITIZE-NORECOVER:       try.cont:
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END10]]
// CHECK-SANITIZE-NORECOVER:       if.end10:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP15:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[CMP11:%.*]] = icmp eq i32 [[TMP15]], 2
// CHECK-SANITIZE-NORECOVER-NEXT:    br i1 [[CMP11]], label [[IF_THEN12:%.*]], label [[IF_END16:%.*]]
// CHECK-SANITIZE-NORECOVER:       if.then12:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SC1Ei(ptr noundef nonnull align 1 dereferenceable(1) [[STATE13]], i32 noundef 600)
// CHECK-SANITIZE-NORECOVER-NEXT:    invoke void @_Z10will_throwi(i32 noundef 700)
// CHECK-SANITIZE-NORECOVER-NEXT:    to label [[INVOKE_CONT15:%.*]] unwind label [[LPAD14:%.*]]
// CHECK-SANITIZE-NORECOVER:       invoke.cont15:
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE13]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[IF_END16]]
// CHECK-SANITIZE-NORECOVER:       lpad14:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP16:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    cleanup
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP17:%.*]] = extractvalue { ptr, i32 } [[TMP16]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    store ptr [[TMP17]], ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP18:%.*]] = extractvalue { ptr, i32 } [[TMP16]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    store i32 [[TMP18]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @_ZN1SD1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[STATE13]]) #[[ATTR7]]
// CHECK-SANITIZE-NORECOVER-NEXT:    br label [[EH_RESUME]]
// CHECK-SANITIZE-NORECOVER:       if.end16:
// CHECK-SANITIZE-NORECOVER-NEXT:    ret void
// CHECK-SANITIZE-NORECOVER:       eh.resume:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[EXN17:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-SANITIZE-NORECOVER-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-SANITIZE-NORECOVER-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } undef, ptr [[EXN17]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    [[LPAD_VAL18:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL]], 1
// CHECK-SANITIZE-NORECOVER-NEXT:    resume { ptr, i32 } [[LPAD_VAL18]]
// CHECK-SANITIZE-NORECOVER:       terminate.lpad:
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP19:%.*]] = landingpad { ptr, i32 }
// CHECK-SANITIZE-NORECOVER-NEXT:    catch ptr null
// CHECK-SANITIZE-NORECOVER-NEXT:    [[TMP20:%.*]] = extractvalue { ptr, i32 } [[TMP19]], 0
// CHECK-SANITIZE-NORECOVER-NEXT:    call void @__clang_call_terminate(ptr [[TMP20]]) #[[ATTR8]]
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
// CHECK-SANITIZE-NORECOVER:       unreachable:
// CHECK-SANITIZE-NORECOVER-NEXT:    unreachable
//
void exception_escape_is_ok(int x) {
  if(x == 0) {
#line 100
    S state;
#line 200
    might_throw();
  }
  if(x == 1) {
    try {
#line 300
      S state;
#line 400
      might_throw();
    } catch (...) {
#line 500
      throw;
    }
  }
  if(x == 2) {
#line 600
    S state;
#line 700
    will_throw();
  }
}
