// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature --check-attributes --check-globals
// RUN: %clang_cc1 -emit-llvm %s -o - -triple x86_64-linux-gnu -std=c++14 -fcxx-exceptions                                | FileCheck %s --check-prefixes=CHECK-ALL,CHECK-NO-EXCEPTIONS
// RUN: %clang_cc1 -emit-llvm %s -o - -triple x86_64-linux-gnu -std=c++14 -fcxx-exceptions -fexceptions                   | FileCheck %s --check-prefixes=CHECK-ALL,CHECK-EXCEPTIONS,CHECK-NORMAL-NOEXCEPT
// RUN: %clang_cc1 -emit-llvm %s -o - -triple x86_64-linux-gnu -std=c++14 -fcxx-exceptions -fexceptions -fstrict-noexcept | FileCheck %s --check-prefixes=CHECK-ALL,CHECK-EXCEPTIONS,CHECK-STRICT-NOEXCEPT

void will_throw_float(int line = __builtin_LINE());

//.
// CHECK-NO-EXCEPTIONS: @_ZTIi = external constant ptr
//.
// CHECK-NORMAL-NOEXCEPT: @_ZTIi = external constant ptr
//.
// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z37exception_escape_is_termination_or_ubi
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z16will_throw_floati(i32 noundef 100)
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-NORMAL-NOEXCEPT: Function Attrs: mustprogress noinline optnone
// CHECK-NORMAL-NOEXCEPT-LABEL: define {{[^@]+}}@_Z37exception_escape_is_termination_or_ubi
// CHECK-NORMAL-NOEXCEPT-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__gxx_personality_v0 {
// CHECK-NORMAL-NOEXCEPT-NEXT:  entry:
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// CHECK-NORMAL-NOEXCEPT-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NORMAL-NOEXCEPT-NEXT:    invoke void @_Z16will_throw_floati(i32 noundef 100)
// CHECK-NORMAL-NOEXCEPT-NEXT:    to label [[INVOKE_CONT:%.*]] unwind label [[LPAD:%.*]]
// CHECK-NORMAL-NOEXCEPT:       invoke.cont:
// CHECK-NORMAL-NOEXCEPT-NEXT:    ret void
// CHECK-NORMAL-NOEXCEPT:       lpad:
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
// CHECK-NORMAL-NOEXCEPT-NEXT:    filter [1 x ptr] [ptr @_ZTIi]
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[TMP1:%.*]] = extractvalue { ptr, i32 } [[TMP0]], 0
// CHECK-NORMAL-NOEXCEPT-NEXT:    store ptr [[TMP1]], ptr [[EXN_SLOT]], align 8
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, i32 } [[TMP0]], 1
// CHECK-NORMAL-NOEXCEPT-NEXT:    store i32 [[TMP2]], ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NORMAL-NOEXCEPT-NEXT:    br label [[FILTER_DISPATCH:%.*]]
// CHECK-NORMAL-NOEXCEPT:       filter.dispatch:
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[EHSPEC_FAILS:%.*]] = icmp slt i32 [[SEL]], 0
// CHECK-NORMAL-NOEXCEPT-NEXT:    br i1 [[EHSPEC_FAILS]], label [[EHSPEC_UNEXPECTED:%.*]], label [[EH_RESUME:%.*]]
// CHECK-NORMAL-NOEXCEPT:       ehspec.unexpected:
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NORMAL-NOEXCEPT-NEXT:    call void @__cxa_call_unexpected(ptr [[EXN]]) #[[ATTR2:[0-9]+]]
// CHECK-NORMAL-NOEXCEPT-NEXT:    unreachable
// CHECK-NORMAL-NOEXCEPT:       eh.resume:
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[EXN1:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[SEL2:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } poison, ptr [[EXN1]], 0
// CHECK-NORMAL-NOEXCEPT-NEXT:    [[LPAD_VAL3:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL2]], 1
// CHECK-NORMAL-NOEXCEPT-NEXT:    resume { ptr, i32 } [[LPAD_VAL3]]
//
// CHECK-STRICT-NOEXCEPT: Function Attrs: mustprogress noinline optnone
// CHECK-STRICT-NOEXCEPT-LABEL: define {{[^@]+}}@_Z37exception_escape_is_termination_or_ubi
// CHECK-STRICT-NOEXCEPT-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-STRICT-NOEXCEPT-NEXT:  entry:
// CHECK-STRICT-NOEXCEPT-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-STRICT-NOEXCEPT-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-STRICT-NOEXCEPT-NEXT:    call void @_Z16will_throw_floati(i32 noundef 100)
// CHECK-STRICT-NOEXCEPT-NEXT:    ret void
//
void exception_escape_is_termination_or_ub(int x) throw(int) {
#line 100
  will_throw_float();
}

// CHECK-NO-EXCEPTIONS: Function Attrs: mustprogress noinline nounwind optnone
// CHECK-NO-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-NO-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0]] {
// CHECK-NO-EXCEPTIONS-NEXT:  entry:
// CHECK-NO-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NO-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NO-EXCEPTIONS-NEXT:    call void @_Z16will_throw_floati(i32 noundef 100)
// CHECK-NO-EXCEPTIONS-NEXT:    ret void
//
// CHECK-EXCEPTIONS: Function Attrs: mustprogress noinline optnone
// CHECK-EXCEPTIONS-LABEL: define {{[^@]+}}@_Z22exception_escape_is_oki
// CHECK-EXCEPTIONS-SAME: (i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-EXCEPTIONS-NEXT:  entry:
// CHECK-EXCEPTIONS-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-EXCEPTIONS-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-EXCEPTIONS-NEXT:    call void @_Z16will_throw_floati(i32 noundef 100)
// CHECK-EXCEPTIONS-NEXT:    ret void
//
void exception_escape_is_ok(int x) {
#line 100
  will_throw_float();
}
//.
// CHECK-NO-EXCEPTIONS: attributes #0 = { mustprogress noinline nounwind optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-NO-EXCEPTIONS: attributes #1 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
//.
// CHECK-NORMAL-NOEXCEPT: attributes #0 = { mustprogress noinline optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-NORMAL-NOEXCEPT: attributes #1 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-NORMAL-NOEXCEPT: attributes #2 = { noreturn }
//.
// CHECK-STRICT-NOEXCEPT: attributes #0 = { mustprogress noinline optnone "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
// CHECK-STRICT-NOEXCEPT: attributes #1 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+cx8,+mmx,+sse,+sse2,+x87" }
//.
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-ALL: {{.*}}
